### ISSUE TITLE
Cache authentication token separate from connection.

### ISSUE THREAD

**Issue by jimsalyer** [willfarrell/middy-rds#11]
We're running into an issue after following a recommendation from AWS to let RDS Proxy manage the caching and pooling of connections instead of doing it within our lambdas. After switching to the proxy, we updated all our lambdas to not cache the connections (and immediately close them) by setting the cacheExpiry to 0, the idleTimeoutMillis to -1, and disabling prefetch. This is starting to cause issues with our larger step functions and lambdas when too many connections are opened within a single second, each with its own authentication token due to the disabling of the caching. Is there a relatively simple way we can enable the caching of just the tokens, but not the connections using the middy-rds library, or are we basically stuck rolling our own connection middleware?

Feel free to close this issue right away, as its not an actual issue. We just wanted to pose the question and see what your thoughts were.

**Comment by willfarrell** [comment]
Sorry, missed this. I think https://middy.js.org/docs/middlewares/rds-signer might be what you're looking for. Then you can combine it with your own custom db connector middleware.
