### ISSUE TITLE
Impossible to load with typescript

### ISSUE THREAD

**Issue by throrin19** [willfarrell/middy-rds#8]
Hello, I have a problem when I want to use your library using Typescript

When I try to use it, I have an error TS2307 (it will be fix with `@ts-ignore`) :
   ![image](https://github.com/willfarrell/middy-rds/assets/1394778/adc4eb03-62c2-4c54-96ec-a6df573b9d01)

**Comment by willfarrell** [comment]
I personally don't use TS, but a PR is welcome.

**Comment by willfarrell** [comment]
Closing due to lack of interest
