### ISSUE TITLE
config.port is undefined

### ISSUE THREAD

**Issue by throrin19** [willfarrell/middy-rds#9]
I think, it was a mistake in the code for the knex part.

At the example, all configuration (including database port) are inside `options.config.connection`. But, in the knex file, We have this mistake : 

https://github.com/willfarrell/middy-rds/blob/262273781169366c156ab0420b44385b124355d2/clients/knex.js#L30-L32

To avoid that, I have to set the `port` in `options.config` and `options.config.connection`

**Comment by willfarrell** [comment]
Thanks, I'll patch that up.
